[package]
name = "rust_lib_hash_calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.28"
recursive-hash-calculator-core = { path = "../core" }

thiserror = "1.0.50" # Custom Errors
