# Source: https://doc.rust-lang.org/cargo/guide/continuous-integration.html

name: Cargo Build & Test

on:
  push:
    branches: ["master"]
  pull_request:

# Make sure CI fails on all warnings
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: .github/scripts/setup.sh
      - run: cargo build --verbose
      - run: cargo test --verbose
